package abccompany.viewClass;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */


import abccompany.controllerClass.BookingOperationsImplement;
import abccompany.database.DatabaseConnection;
import java.sql.PreparedStatement;
import abccompany.modelClass.Booking;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import java.time.temporal.ChronoUnit;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.ResultSet;







public class AddBooking extends javax.swing.JFrame {

    /**
     * Creates new form AddBooking
     */
    public AddBooking() {
        initComponents();
        Load();
    }
    
    public int getDaysBetween() {
         Date start=jDateCheck.getCalendar().getTime();
        Date end=jDateCheckOut.getCalendar().getTime();
        
        LocalDate startDate=LocalDate.ofInstant(start.toInstant(),ZoneId.systemDefault());
        LocalDate endDate=LocalDate.ofInstant(end.toInstant(), ZoneId.systemDefault());
        return (int) ChronoUnit.DAYS.between(startDate, endDate);
    }
    public double totalPrice(){
        double price=Double.parseDouble(hallPriceTxt.getText());
        double totalPrice=price*getDaysBetween();
        return totalPrice;
        
        
    }

    public void getPricePerDay(){
        int hallId=Integer.parseInt(editHallId.getText());
        
        try{
            Connection con=DatabaseConnection.getConnection();
            String sql="select * from hall where idHall=?";
            PreparedStatement pst=con.prepareStatement(sql);
            pst.setInt(1,hallId);
            ResultSet rs=pst.executeQuery();
            
            if(rs.next()){
                hallPriceTxt.setText(rs.getString("hallPricePerDay"));
            }else{
                hallPriceTxt.setText("Invalid hall Id");
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    
    public double discountFivePercent(){
        double newPrice=totalPrice()*0.05;
        return newPrice;
        
    }
    
    public double discountTenPercent(){
        double newPrice=totalPrice()*0.10;
        return newPrice;
        
    }
        
    
      public void Load(){
    
        
        BookingOperationsImplement imp = new BookingOperationsImplement();
        List<Booking> list =imp.list(); 
        DefaultTableModel DFT =(DefaultTableModel) bookTable.getModel();
        DFT.setRowCount(0);
        for(Booking st : list){
        
        int bid = st.getBookingId();
        int cid= st.getCustomerId();
        int hid= st.getHallId();
     
        LocalDate startDate=st.getStartDate();
        LocalDate endDate=st.getEndDate();
       
        
        DFT.addRow(new Object[]{bid,cid,hid,startDate,endDate});
        
        }
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        editBookId = new javax.swing.JTextField();
        addBookingBtn = new javax.swing.JButton();
        jDateCheck = new com.toedter.calendar.JDateChooser();
        jDateCheckOut = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookTable = new javax.swing.JTable();
        searchBookingBtn = new javax.swing.JButton();
        editBookingBtn = new javax.swing.JButton();
        deleteBookingBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        editCustomerId = new javax.swing.JTextField();
        editHallId = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        viewPriceBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        hallPriceTxt = new javax.swing.JTextField();
        totalPriceTxt = new javax.swing.JTextField();
        paymentBtn = new javax.swing.JButton();
        viewHallBtn = new javax.swing.JButton();
        fiveBtn = new javax.swing.JButton();
        tenBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        discountTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Book Hall");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 126, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Check In Date");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 100, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Booking ID");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 79, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Check Out Date");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 110, -1));
        jPanel1.add(editBookId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 100, -1));

        addBookingBtn.setBackground(new java.awt.Color(51, 102, 0));
        addBookingBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBookingBtn.setText("Add booking");
        addBookingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookingBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addBookingBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 110, -1));
        jPanel1.add(jDateCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 185, -1));
        jPanel1.add(jDateCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 185, -1));

        bookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Booking ID", "Customer ID", "Hall ID", "Checking Date", "Check Out Date"
            }
        ));
        jScrollPane1.setViewportView(bookTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 460, 350));

        searchBookingBtn.setBackground(new java.awt.Color(51, 102, 0));
        searchBookingBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBookingBtn.setText("Search Booking");
        searchBookingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBookingBtnActionPerformed(evt);
            }
        });
        jPanel1.add(searchBookingBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, -1, -1));

        editBookingBtn.setBackground(new java.awt.Color(51, 102, 0));
        editBookingBtn.setForeground(new java.awt.Color(255, 255, 255));
        editBookingBtn.setText("Update Booking");
        editBookingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBookingBtnActionPerformed(evt);
            }
        });
        jPanel1.add(editBookingBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, -1, -1));

        deleteBookingBtn.setBackground(new java.awt.Color(51, 102, 0));
        deleteBookingBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBookingBtn.setText("Delete Booking");
        deleteBookingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBookingBtnActionPerformed(evt);
            }
        });
        jPanel1.add(deleteBookingBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Customer ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Hall ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 50, -1));
        jPanel1.add(editCustomerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 100, -1));

        editHallId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                editHallIdFocusLost(evt);
            }
        });
        editHallId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editHallIdActionPerformed(evt);
            }
        });
        jPanel1.add(editHallId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 100, -1));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 30));

        viewPriceBtn.setBackground(new java.awt.Color(0, 51, 51));
        viewPriceBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewPriceBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewPriceBtn.setText("View total price");
        viewPriceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPriceBtnActionPerformed(evt);
            }
        });
        jPanel1.add(viewPriceBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 120, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Hall price per day");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        hallPriceTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hallPriceTxtActionPerformed(evt);
            }
        });
        jPanel1.add(hallPriceTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 100, -1));

        totalPriceTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalPriceTxtActionPerformed(evt);
            }
        });
        jPanel1.add(totalPriceTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 150, -1));

        paymentBtn.setBackground(new java.awt.Color(0, 51, 51));
        paymentBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        paymentBtn.setForeground(new java.awt.Color(255, 255, 255));
        paymentBtn.setText("Make Payment");
        paymentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentBtnActionPerformed(evt);
            }
        });
        jPanel1.add(paymentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 440, -1, -1));

        viewHallBtn.setBackground(new java.awt.Color(0, 51, 51));
        viewHallBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewHallBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewHallBtn.setText("View Halls");
        viewHallBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewHallBtnActionPerformed(evt);
            }
        });
        jPanel1.add(viewHallBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, -1, -1));

        fiveBtn.setText("5% discount");
        fiveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveBtnActionPerformed(evt);
            }
        });
        jPanel1.add(fiveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        tenBtn.setText("10% discount");
        tenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenBtnActionPerformed(evt);
            }
        });
        jPanel1.add(tenBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, -1, -1));

        jLabel5.setText("Discounted total price");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 70, -1));

        discountTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountTxtActionPerformed(evt);
            }
        });
        jPanel1.add(discountTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 100, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-9, 0, 1010, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBookingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookingBtnActionPerformed
        // TODO add your handling code here:
        Booking obj=new Booking();
        int bId=Integer.parseInt(editBookId.getText());
        int cId=Integer.parseInt(editCustomerId.getText());
        int hId=Integer.parseInt(editHallId.getText());
      
        
        Date start=jDateCheck.getCalendar().getTime();
        Date end=jDateCheckOut.getCalendar().getTime();
        
        LocalDate startDate=LocalDate.ofInstant(start.toInstant(),ZoneId.systemDefault());
        LocalDate endDate=LocalDate.ofInstant(end.toInstant(), ZoneId.systemDefault());
        
       
        
        obj.setBookingId(bId);
        obj.setCustomerId(cId);
        obj.setHallId(hId);
        obj.setStartDate(startDate);
        obj.setEndDate(endDate);
        
        
        BookingOperationsImplement imp= new BookingOperationsImplement();
        imp.save(obj);
        
        Load();
        
        editBookId.setText("");
        editCustomerId.setText("");
        editHallId.setText("");
        hallPriceTxt.setText("");
        jDateCheck.setCalendar(null);
        jDateCheckOut.setCalendar(null);
        totalPriceTxt.setText("");
       
        
        
    }//GEN-LAST:event_addBookingBtnActionPerformed
   int search;
    private void searchBookingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBookingBtnActionPerformed
        // TODO add your handling code here:
        search=Integer.parseInt(JOptionPane.showInputDialog("Enter Booking ID"));
        
        BookingOperationsImplement dao=new BookingOperationsImplement();
         Booking st =dao.getDetails(search);
       
       editBookId.setText(String.valueOf(st.getBookingId()));
       editCustomerId.setText(String.valueOf(st.getCustomerId()));
       editHallId.setText(String.valueOf(st.getHallId()));
       
       jDateCheck.setDate(Date.from(st.getStartDate().atStartOfDay(ZoneId.systemDefault()).toInstant()));
       jDateCheckOut.setDate(Date.from(st.getEndDate().atStartOfDay(ZoneId.systemDefault()).toInstant()));
       
    
     
     
    }//GEN-LAST:event_searchBookingBtnActionPerformed

    private void deleteBookingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBookingBtnActionPerformed
        // TODO add your handling code here:
         Booking st=new Booking();
        st.setBookingId(search);
        BookingOperationsImplement dao= new BookingOperationsImplement();
        dao.delete(st);
        Load();
        
        editBookId.setText("");
        editCustomerId.setText("");
        editHallId.setText("");
        jDateCheck.setCalendar(null);
        jDateCheckOut.setCalendar(null);
        
    }//GEN-LAST:event_deleteBookingBtnActionPerformed

    private void viewPriceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPriceBtnActionPerformed
         
        totalPriceTxt.setText(String.valueOf(totalPrice()));
    }//GEN-LAST:event_viewPriceBtnActionPerformed

    private void editHallIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editHallIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editHallIdActionPerformed

    private void editHallIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editHallIdFocusLost
        // TODO add your handling code here:
        getPricePerDay();
            
        
    }//GEN-LAST:event_editHallIdFocusLost

    private void hallPriceTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hallPriceTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hallPriceTxtActionPerformed

    private void editBookingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBookingBtnActionPerformed
        // TODO add your handling code here:
          Booking st=new Booking();
          int cId=Integer.parseInt(editCustomerId.getText());
          int hId=Integer.parseInt(editHallId.getText());
          Date start=jDateCheck.getCalendar().getTime();
          Date end=jDateCheckOut.getCalendar().getTime();
        
        LocalDate startDate=LocalDate.ofInstant(start.toInstant(),ZoneId.systemDefault());
        LocalDate endDate=LocalDate.ofInstant(end.toInstant(), ZoneId.systemDefault());
        
       
        
        
        st.setCustomerId(cId);
        st.setHallId(hId);
        st.setStartDate(startDate);
        st.setEndDate(endDate);
         st.setBookingId(search);



     
         BookingOperationsImplement imp= new BookingOperationsImplement();
          imp.edit(st);
       
         Load();
        editBookId.setText("");
        editCustomerId.setText("");
        editHallId.setText("");
        hallPriceTxt.setText("");
        jDateCheck.setCalendar(null);
        jDateCheckOut.setCalendar(null);
        totalPriceTxt.setText("");
       
        
       
    }//GEN-LAST:event_editBookingBtnActionPerformed

    private void paymentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentBtnActionPerformed
        // TODO add your handling code here:
         dispose(); 
        Payment hpage= new Payment();
        hpage.show();
    }//GEN-LAST:event_paymentBtnActionPerformed

    private void viewHallBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewHallBtnActionPerformed
        // TODO add your handling code here:
         dispose();
        AddHall hpage= new AddHall();
        hpage.show();
    }//GEN-LAST:event_viewHallBtnActionPerformed

    private void totalPriceTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalPriceTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalPriceTxtActionPerformed

    private void fiveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveBtnActionPerformed
        // TODO add your handling code here:
        
        discountTxt.setText(String.valueOf(discountFivePercent()));
        
        
    }//GEN-LAST:event_fiveBtnActionPerformed

    private void tenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenBtnActionPerformed
        // TODO add your handling code here:
        discountTxt.setText(String.valueOf(discountTenPercent()));
    }//GEN-LAST:event_tenBtnActionPerformed

    private void discountTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discountTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBookingBtn;
    private javax.swing.JTable bookTable;
    private javax.swing.JButton deleteBookingBtn;
    private javax.swing.JTextField discountTxt;
    private javax.swing.JTextField editBookId;
    private javax.swing.JButton editBookingBtn;
    private javax.swing.JTextField editCustomerId;
    private javax.swing.JTextField editHallId;
    private javax.swing.JButton fiveBtn;
    private javax.swing.JTextField hallPriceTxt;
    private com.toedter.calendar.JDateChooser jDateCheck;
    private com.toedter.calendar.JDateChooser jDateCheckOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton paymentBtn;
    private javax.swing.JButton searchBookingBtn;
    private javax.swing.JButton tenBtn;
    private javax.swing.JTextField totalPriceTxt;
    private javax.swing.JButton viewHallBtn;
    private javax.swing.JButton viewPriceBtn;
    // End of variables declaration//GEN-END:variables
}
