/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package abccompany.viewClass;

import abccompany.controllerClass.CustomerOperationsImplement;
import abccompany.modelClass.Customer;
import java.util.List;


import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class AddCustomer extends javax.swing.JFrame {

    /**
     * Creates new form AddCustomer
     */
    public AddCustomer() {
        initComponents();
        Load();
    }
    
    public void Load(){
    
        
        CustomerOperationsImplement imp = new CustomerOperationsImplement();
        List<Customer> list =imp.list();
        DefaultTableModel DFT =(DefaultTableModel) customerTable.getModel();
        DFT.setRowCount(0);
        for(Customer st : list){
        
        int cid = st.getCustomerId();
        String cName= st.getName();
        String cNic=st.getNic();
        String cContact = st.getContactNo();
        DFT.addRow(new Object[]{cid,cName,cNic,cContact});
        
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        editId = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        editName = new javax.swing.JTextField();
        editNic = new javax.swing.JTextField();
        editContact = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        UpdateBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        bookHallBtn = new javax.swing.JButton();
        addHallBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Customer Details");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 210, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Customer ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 100, -1));
        jPanel1.add(editId, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 140, -1));

        addBtn.setBackground(new java.awt.Color(0, 102, 0));
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("Add Customer");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 120, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Customer Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 120, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Customer NIC");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 110, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Contact Number");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 120, -1));
        jPanel1.add(editName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 140, -1));
        jPanel1.add(editNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 140, -1));
        jPanel1.add(editContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 140, 20));

        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Customer ID", "Customer Name", "Customer NIC", " Contact Number"
            }
        ));
        jScrollPane1.setViewportView(customerTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 470, 380));

        UpdateBtn.setBackground(new java.awt.Color(51, 102, 0));
        UpdateBtn.setForeground(new java.awt.Color(255, 255, 255));
        UpdateBtn.setText("Update Customer");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });
        jPanel1.add(UpdateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 130, -1));

        searchBtn.setBackground(new java.awt.Color(51, 102, 0));
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setText("Search Customer");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        jPanel1.add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 130, -1));

        deleteBtn.setBackground(new java.awt.Color(51, 102, 0));
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Delete Customer");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 130, -1));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 40));

        bookHallBtn.setBackground(new java.awt.Color(0, 51, 51));
        bookHallBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bookHallBtn.setForeground(new java.awt.Color(255, 255, 255));
        bookHallBtn.setText("Book Hall");
        bookHallBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookHallBtnActionPerformed(evt);
            }
        });
        jPanel1.add(bookHallBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, -1, -1));

        addHallBtn.setBackground(new java.awt.Color(0, 51, 51));
        addHallBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addHallBtn.setForeground(new java.awt.Color(255, 255, 255));
        addHallBtn.setText("Back");
        addHallBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHallBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addHallBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int search;
    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
         search=Integer.parseInt(JOptionPane.showInputDialog("Enter customer ID"));
        
         CustomerOperationsImplement dao=new CustomerOperationsImplement();
         Customer st =dao.getDetails(search);
        
        
        editName.setText(st.getName());
        editNic.setText(st.getNic());
        editContact.setText(st.getContactNo());
    }//GEN-LAST:event_searchBtnActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        // TODO add your handling code here:
        Customer st=new Customer();
        String cName=editName.getText();
        String cNic=editNic.getText();
        String cContact=editContact.getText();
        
        
        st.setName(cName);
        st.setNic(cNic);
        st.setContactNo(cContact);
        st.setCustomerId(search);
        
        CustomerOperationsImplement imp= new CustomerOperationsImplement();
        imp.edit(st);
        
        Load();
        
        
        editName.setText("");
        editNic.setText("");
        editContact.setText("");
        editName.requestFocus();;
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        Customer obj=new Customer();
        int cId=Integer.parseInt(editId.getText());
        String cName=editName.getText();
        String cNic=editNic.getText();
        String cContact=editContact.getText();
        
        obj.setCustomerId(cId);
        obj.setName(cName);
        obj.setNic(cNic);
        obj.setContactNo(cContact);
        
        CustomerOperationsImplement imp= new CustomerOperationsImplement();
        imp.save(obj);
        
        Load();
        
        editId.setText("");
        editName.setText("");
        editNic.setText("");
        editContact.setText("");
        editName.requestFocus();;
    }//GEN-LAST:event_addBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
         Customer st=new Customer();
         st.setCustomerId(search);
         CustomerOperationsImplement dao= new CustomerOperationsImplement();
         dao.delete(st);
         Load();
        
        editName.setText("");
        editNic.setText("");
        editContact.setText("");
        editName.requestFocus();;
                                  
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void bookHallBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookHallBtnActionPerformed
        // TODO add your handling code here:
          dispose();
        AddBooking page = new AddBooking();
        page.show();
    }//GEN-LAST:event_bookHallBtnActionPerformed

    private void addHallBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHallBtnActionPerformed
        // TODO add your handling code here:
         dispose(); 
        Welcome hpage= new Welcome();
        hpage.show();
    }//GEN-LAST:event_addHallBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton addHallBtn;
    private javax.swing.JButton bookHallBtn;
    private javax.swing.JTable customerTable;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField editContact;
    private javax.swing.JTextField editId;
    private javax.swing.JTextField editName;
    private javax.swing.JTextField editNic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchBtn;
    // End of variables declaration//GEN-END:variables
}
