package abccompany.viewClass;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import abccompany.controllerClass.HallOperationsImplement;
import abccompany.modelClass.Hall;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author DELL
 */
public class AddHall extends javax.swing.JFrame {

    /**
     * Creates new form AddHall
     */
    public AddHall() {
        initComponents();
        Load();
    }

    
     public void Load(){
    
        
        HallOperationsImplement imp = new HallOperationsImplement();
        List<Hall> list =imp.list();
        DefaultTableModel DFT =(DefaultTableModel) editTable.getModel();
        DFT.setRowCount(0);
        for(Hall st : list){
        
        int hid = st.getIdHall();
        String hType= st.getHallType();
        String hName=st.getHallName();
        Double fee = st.getHallPrice();
        DFT.addRow(new Object[]{hid,hType,hName,fee});
        
        }
    
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        editIdHall = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        editHallPrice = new javax.swing.JTextField();
        addHallBtn = new javax.swing.JButton();
        searchHallBtn = new javax.swing.JButton();
        cmbeditHallType = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        editTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        editHallName = new javax.swing.JTextField();
        deleteHallBtn = new javax.swing.JButton();
        editHallBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        addCustomerbtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Add Hall");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 119, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Hall Type");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 170, 70, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Hall ID");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 118, -1, -1));

        editIdHall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editIdHallActionPerformed(evt);
            }
        });
        jPanel1.add(editIdHall, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 115, 129, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Hall Price per day");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 246, 130, -1));
        jPanel1.add(editHallPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 243, 129, -1));

        addHallBtn.setBackground(new java.awt.Color(51, 102, 0));
        addHallBtn.setForeground(new java.awt.Color(255, 255, 255));
        addHallBtn.setText("Add hall");
        addHallBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHallBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addHallBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 322, 88, -1));

        searchHallBtn.setBackground(new java.awt.Color(51, 102, 0));
        searchHallBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchHallBtn.setText("Search Hall");
        searchHallBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchHallBtnActionPerformed(evt);
            }
        });
        jPanel1.add(searchHallBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 100, -1));

        cmbeditHallType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Small ", "Medium", "Large", " " }));
        cmbeditHallType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbeditHallTypeActionPerformed(evt);
            }
        });
        jPanel1.add(cmbeditHallType, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 163, 129, -1));

        editTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Hall ID", "Hall Type", "Hall Name", "Hall Price per day"
            }
        ));
        jScrollPane1.setViewportView(editTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 499, 448));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Hall Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 206, 90, -1));
        jPanel1.add(editHallName, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 203, 129, -1));

        deleteHallBtn.setBackground(new java.awt.Color(51, 102, 0));
        deleteHallBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteHallBtn.setText("Delete hall");
        deleteHallBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteHallBtnActionPerformed(evt);
            }
        });
        jPanel1.add(deleteHallBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 377, -1, -1));

        editHallBtn.setBackground(new java.awt.Color(51, 102, 0));
        editHallBtn.setForeground(new java.awt.Color(255, 255, 255));
        editHallBtn.setText("Update Hall");
        editHallBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editHallBtnActionPerformed(evt);
            }
        });
        jPanel1.add(editHallBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 377, 100, -1));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 40));

        addCustomerbtn.setBackground(new java.awt.Color(0, 51, 51));
        addCustomerbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addCustomerbtn.setForeground(new java.awt.Color(255, 255, 255));
        addCustomerbtn.setText("Add customer");
        addCustomerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerbtnActionPerformed(evt);
            }
        });
        jPanel1.add(addCustomerbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, -1, -1));

        backBtn.setBackground(new java.awt.Color(0, 51, 51));
        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editIdHallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editIdHallActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editIdHallActionPerformed

    private void addHallBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHallBtnActionPerformed
        // TODO add your handling code here:
        
        Hall obj=new Hall();
        int hId=Integer.parseInt(editIdHall.getText());
        String hType=cmbeditHallType.getModel().getSelectedItem().toString();
        String hName=editHallName.getText();
        double fee=Double.parseDouble(editHallPrice.getText());
        
        obj.setIdHall(hId);
        obj.setType(hType);
        obj.setHallName(hName);
        obj.setHallPrice(fee);
        
        HallOperationsImplement imp= new HallOperationsImplement();
        imp.save(obj);
        
        Load();
        
        editIdHall.setText("");
        cmbeditHallType.setSelectedItem("");
        editHallName.setText("");
        editHallPrice.setText("");
        cmbeditHallType.requestFocus();;
        
    }//GEN-LAST:event_addHallBtnActionPerformed

    
    private void editHallBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editHallBtnActionPerformed
        // TODO add your handling code here:
        Hall st=new Hall();
        String hType=cmbeditHallType.getSelectedItem().toString();
        String hName=editHallName.getText();
        double fee=Double.parseDouble(editHallPrice.getText());
        
        st.setType(hType);
        st.setHallName(hName);
        st.setHallPrice(fee);
        st.setIdHall(search);
        
         HallOperationsImplement imp= new HallOperationsImplement();
         imp.edit(st);
        
        Load();
        
        cmbeditHallType.setSelectedItem("");
        editHallName.setText("");
        editHallPrice.setText("");
        cmbeditHallType.requestFocus();
        
    }//GEN-LAST:event_editHallBtnActionPerformed

    private void deleteHallBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteHallBtnActionPerformed
        // TODO add your handling code here:
        Hall st=new Hall();
         st.setIdHall(search);
         HallOperationsImplement dao= new HallOperationsImplement();
         dao.delete(st);
         Load();
        
        cmbeditHallType.setSelectedItem("");
        editHallName.setText("");
        editHallPrice.setText("");
        cmbeditHallType.requestFocus();
                                  
    }//GEN-LAST:event_deleteHallBtnActionPerformed

    int search;
    private void searchHallBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchHallBtnActionPerformed
        // TODO add your handling code here:
        
        search = Integer.parseInt(JOptionPane.showInputDialog("Enter Hall ID"));

    HallOperationsImplement dao = new HallOperationsImplement();
    Hall st = dao.getDetails(search);

    // Set the hall details to the text fields
    editHallName.setText(st.getHallName());
    editHallPrice.setText(String.valueOf(st.getHallPrice()));

    // Set the relevant value in the combo box
    String type = st.getHallType();
    cmbeditHallType.setSelectedItem(type);
        
        
        
  
    }//GEN-LAST:event_searchHallBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        Welcome page = new Welcome();
        page.show();
    }//GEN-LAST:event_backBtnActionPerformed

    private void addCustomerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerbtnActionPerformed
        // TODO add your handling code here:
          dispose();
        AddCustomer page = new AddCustomer();
        page.show();
    }//GEN-LAST:event_addCustomerbtnActionPerformed

    private void cmbeditHallTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbeditHallTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbeditHallTypeActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddHall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddHall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddHall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddHall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AddHall().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustomerbtn;
    private javax.swing.JButton addHallBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox<String> cmbeditHallType;
    private javax.swing.JButton deleteHallBtn;
    private javax.swing.JButton editHallBtn;
    private javax.swing.JTextField editHallName;
    private javax.swing.JTextField editHallPrice;
    private javax.swing.JTextField editIdHall;
    private javax.swing.JTable editTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchHallBtn;
    // End of variables declaration//GEN-END:variables

}